# Generated by Django 3.2.16 on 2024-08-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_coach', to=settings.AUTH_USER_MODEL, verbose_name='тренер'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='спортсмен'),
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diary', to=settings.AUTH_USER_MODEL, verbose_name='спортсмен'),
        ),
        migrations.AddField(
            model_name='bodystatsdiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodystats_diary', to=settings.AUTH_USER_MODEL, verbose_name='спортсмен'),
        ),
        migrations.AddConstraint(
            model_name='fooddiary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_food_diary'),
        ),
        migrations.AddConstraint(
            model_name='bodystatsdiary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_bodystats_diary'),
        ),
    ]
