# Generated by Django 3.2.16 on 2023-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20230719_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='проект закрыт'),
        ),
    ]
