# Generated by Django 3.2.16 on 2026-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('section', models.CharField(max_length=200, verbose_name='раздел')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='изображение')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('youtube_id', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
