# Generated by Django 3.2.16 on 2026-08-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='дата')),
                ('phase', models.CharField(choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], max_length=20, verbose_name='фаза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_overrides', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Phase override',
                'verbose_name_plural': 'Phase overrides',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='дата начала цикла')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_entries', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Period entry',
                'verbose_name_plural': 'Period entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length_days', models.PositiveSmallIntegerField(default=28, verbose_name='длина цикла в днях')),
                ('period_length_days', models.PositiveSmallIntegerField(default=5, verbose_name='длина менструации в днях')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_settings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phaseoverride',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_phase_override_user_date'),
        ),
    ]
